
var additionalService    = require('./additionalService'),
    admin                = require('./admin'),
    customer             = require('./customer'),
    customerAppVersion   = require('./customerAppVersion'),
    customerNotification = require('./customerNotification'),
    driver               = require('./driver'),
    driverAppVersion     = require('./driverAppVersion'),
    driverNotification   = require('./driverNotification'),
    material             = require('./material'),
    order                = require('./order'),
    orderGenerator       = require('./orderGenerator'),
    partnerQuote         = require('./partnerQuote'),
    promo                = require('./promo'),
    referral             = require('./referral'),
    service              = require('./service'),
    serviceScope         = require('./serviceScope'),
    superAdmin           = require('./superAdmin'),
    vehicle              = require('./vehicle');

module.exports = {
    additionalService    : additionalService,
    admin                : admin,
    customer             : customer,
    customerAppVersion   : customerAppVersion,
    customerNotification : customerNotification,
    driver               : driver,
    driverAppVersion     : driverAppVersion,
    driverNotification   : driverNotification,
    material             : material,
    order                : order,
    orderGenerator       : orderGenerator,
    partnerQuote         : partnerQuote,
    promo                : promo,
    referral             : referral,
    service              : service,
    serviceScope         : serviceScope,
    superAdmin           : superAdmin,
    vehicle              : vehicle
};